In [42]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [44]:
dataset = pd.read_csv(r'/content/Churn_Modelling.csv')

In [45]:
X

array([[-0.99720391,  0.99720391, -0.57380915, ...,  0.64609167,
         0.97024255,  0.02188649],
       [ 1.00280393, -1.00280393,  1.74273971, ..., -1.54776799,
         0.97024255,  0.21653375],
       [-0.99720391,  0.99720391, -0.57380915, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [-0.99720391,  0.99720391, -0.57380915, ..., -1.54776799,
         0.97024255, -1.00864308],
       [ 1.00280393, -1.00280393, -0.57380915, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [-0.99720391,  0.99720391, -0.57380915, ...,  0.64609167,
        -1.03067011, -1.07636976]])

In [46]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [47]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [48]:
X

array([[-0.99720391,  0.99720391,  0.        , ...,  0.64609167,
         0.97024255,  0.02188649],
       [ 1.00280393, -1.00280393,  1.        , ..., -1.54776799,
         0.97024255,  0.21653375],
       [-0.99720391,  0.99720391,  0.        , ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [-0.99720391,  0.99720391,  0.        , ..., -1.54776799,
         0.97024255, -1.00864308],
       [ 1.00280393, -1.00280393,  0.        , ...,  0.64609167,
        -1.03067011, -0.12523071],
       [-0.99720391,  0.99720391,  0.        , ...,  0.64609167,
        -1.03067011, -1.07636976]])

In [49]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [50]:
X

array([[ 0.        ,  1.        , -0.99720391, ...,  0.64609167,
         0.97024255,  0.02188649],
       [ 1.        ,  0.        ,  1.00280393, ..., -1.54776799,
         0.97024255,  0.21653375],
       [ 0.        ,  1.        , -0.99720391, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 0.        ,  1.        , -0.99720391, ..., -1.54776799,
         0.97024255, -1.00864308],
       [ 1.        ,  0.        ,  1.00280393, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 0.        ,  1.        , -0.99720391, ...,  0.64609167,
        -1.03067011, -1.07636976]])

In [51]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [52]:
X

array([[-0.99720391,  0.99720391, -0.99720391, ...,  0.64609167,
         0.97024255,  0.02188649],
       [ 1.00280393, -1.00280393,  1.00280393, ..., -1.54776799,
         0.97024255,  0.21653375],
       [-0.99720391,  0.99720391, -0.99720391, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [-0.99720391,  0.99720391, -0.99720391, ..., -1.54776799,
         0.97024255, -1.00864308],
       [ 1.00280393, -1.00280393,  1.00280393, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [-0.99720391,  0.99720391, -0.99720391, ...,  0.64609167,
        -1.03067011, -1.07636976]])

In [53]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [54]:
ann = tf.keras.models.Sequential()

In [55]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [56]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [57]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [58]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [59]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.6206 - loss: 0.6904
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7963 - loss: 0.4855
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8014 - loss: 0.4535
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8158 - loss: 0.4292
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8183 - loss: 0.4215
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8138 - loss: 0.4270
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8161 - loss: 0.4254
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8292 - loss: 0.4078
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8348 - loss: 0.3992
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8389 - loss: 0.3977
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8380 - loss: 0.3935
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━

In [60]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [61]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1526   69]
 [ 199  206]]
